"""add head_office_vendor_payments table

Revision ID: 03c770c71e68
Revises: e3fe106ebd00
Create Date: 2026-06-12 01:48:51.439064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03c770c71e68'
down_revision = 'e3fe106ebd00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('head_office_vendor_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('paid_from_account_id', sa.Integer(), nullable=True),
    sa.Column('payment_method', sa.String(length=40), nullable=False),
    sa.Column('reference_number', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('is_posted', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['paid_from_account_id'], ['cash_bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('head_office_vendor_payments')
    # ### end Alembic commands ###
