"""stock movements ledger + machine reading tank decrement

Revision ID: 09a6a2a54e5c
Revises: 1546c66b1f4a
Create Date: 2026-06-12 03:52:57.656359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09a6a2a54e5c'
down_revision = '1546c66b1f4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('petrol_pump_id', sa.Integer(), nullable=False),
    sa.Column('tank_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(length=40), nullable=False),
    sa.Column('quantity_liters', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('movement_date', sa.Date(), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['petrol_pump_id'], ['petrol_pumps.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tank_id'], ['pump_tanks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('machine_readings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tank_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column(
            'stock_posted', sa.Boolean(), nullable=False,
            server_default=sa.text('0'),
        ))
        batch_op.create_foreign_key(
            'fk_machine_readings_tank_id', 'pump_tanks', ['tank_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine_readings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_machine_readings_tank_id', type_='foreignkey')
        batch_op.drop_column('stock_posted')
        batch_op.drop_column('tank_id')

    op.drop_table('stock_movements')
    # ### end Alembic commands ###
