"""pump machine fuel product (single product per machine)

Revision ID: 0c215c0522cc
Revises: 956f986a8004
Create Date: 2026-06-13 16:21:50.125368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c215c0522cc'
down_revision = '956f986a8004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pump_machines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_pump_machines_product_id', 'products', ['product_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pump_machines', schema=None) as batch_op:
        batch_op.drop_constraint('fk_pump_machines_product_id', type_='foreignkey')
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###
