"""sync model drift (customers.petrol_pump_id etc.)

Revision ID: 1f1126267aec
Revises: 0c215c0522cc
Create Date: 2026-06-22 15:55:49.277718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f1126267aec'
down_revision = '0c215c0522cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('head_office_staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_name', sa.String(length=150), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('cnic', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('monthly_salary', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('joining_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carriage_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_category_id', sa.Integer(), nullable=True),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('paid_from_account_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('is_posted', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['expense_category_id'], ['expense_categories.id'], ),
    sa.ForeignKeyConstraint(['paid_from_account_id'], ['cash_bank_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('head_office_salary_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('for_month', sa.String(length=40), nullable=True),
    sa.Column('paid_from_account_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('is_posted', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['paid_from_account_id'], ['cash_bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['head_office_staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pump_carriage_cash_feeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('petrol_pump_id', sa.Integer(), nullable=False),
    sa.Column('feed_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('into_account_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('is_posted', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['into_account_id'], ['cash_bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['petrol_pump_id'], ['petrol_pumps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pso_card_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('petrol_pump_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('daily_closing_id', sa.Integer(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by_id', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['daily_closing_id'], ['pump_daily_closings.id'], ),
    sa.ForeignKeyConstraint(['petrol_pump_id'], ['petrol_pumps.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cash_bank_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('petrol_pump_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_cash_bank_accounts_petrol_pump_id', 'petrol_pumps', ['petrol_pump_id'], ['id'])

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('petrol_pump_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_customers_petrol_pump_id', 'petrol_pumps', ['petrol_pump_id'], ['id'])

    with op.batch_alter_table('pump_daily_closings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_account_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bank_posted_account_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bank_posted_amount', sa.Numeric(precision=16, scale=2), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('bank_card_account_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pso_card_account_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('easypaisa_account_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('jazzcash_account_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bank_transfer_account_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('deposit_posted', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('credit_customer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_pdc_bank_transfer_account_id', 'cash_bank_accounts', ['bank_transfer_account_id'], ['id'])
        batch_op.create_foreign_key('fk_pdc_bank_account_id', 'cash_bank_accounts', ['bank_account_id'], ['id'])
        batch_op.create_foreign_key('fk_pdc_bank_posted_account_id', 'cash_bank_accounts', ['bank_posted_account_id'], ['id'])
        batch_op.create_foreign_key('fk_pdc_pso_card_account_id', 'cash_bank_accounts', ['pso_card_account_id'], ['id'])
        batch_op.create_foreign_key('fk_pdc_easypaisa_account_id', 'cash_bank_accounts', ['easypaisa_account_id'], ['id'])
        batch_op.create_foreign_key('fk_pdc_jazzcash_account_id', 'cash_bank_accounts', ['jazzcash_account_id'], ['id'])
        batch_op.create_foreign_key('fk_pdc_bank_card_account_id', 'cash_bank_accounts', ['bank_card_account_id'], ['id'])
        batch_op.create_foreign_key('fk_pdc_credit_customer_id', 'customers', ['credit_customer_id'], ['id'])

    with op.batch_alter_table('pump_machines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tank_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_pump_machines_tank_id', 'pump_tanks', ['tank_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pump_machines', schema=None) as batch_op:
        batch_op.drop_constraint('fk_pump_machines_tank_id', type_='foreignkey')
        batch_op.drop_column('tank_id')

    with op.batch_alter_table('pump_daily_closings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_pdc_bank_transfer_account_id', type_='foreignkey')
        batch_op.drop_constraint('fk_pdc_bank_account_id', type_='foreignkey')
        batch_op.drop_constraint('fk_pdc_bank_posted_account_id', type_='foreignkey')
        batch_op.drop_constraint('fk_pdc_pso_card_account_id', type_='foreignkey')
        batch_op.drop_constraint('fk_pdc_easypaisa_account_id', type_='foreignkey')
        batch_op.drop_constraint('fk_pdc_jazzcash_account_id', type_='foreignkey')
        batch_op.drop_constraint('fk_pdc_bank_card_account_id', type_='foreignkey')
        batch_op.drop_constraint('fk_pdc_credit_customer_id', type_='foreignkey')
        batch_op.drop_column('credit_customer_id')
        batch_op.drop_column('deposit_posted')
        batch_op.drop_column('bank_transfer_account_id')
        batch_op.drop_column('jazzcash_account_id')
        batch_op.drop_column('easypaisa_account_id')
        batch_op.drop_column('pso_card_account_id')
        batch_op.drop_column('bank_card_account_id')
        batch_op.drop_column('bank_posted_amount')
        batch_op.drop_column('bank_posted_account_id')
        batch_op.drop_column('bank_account_id')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_customers_petrol_pump_id', type_='foreignkey')
        batch_op.drop_column('petrol_pump_id')

    with op.batch_alter_table('cash_bank_accounts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cash_bank_accounts_petrol_pump_id', type_='foreignkey')
        batch_op.drop_column('petrol_pump_id')

    op.drop_table('pso_card_payments')
    op.drop_table('pump_carriage_cash_feeds')
    op.drop_table('head_office_salary_payments')
    op.drop_table('carriage_expenses')
    op.drop_table('head_office_staff')
    # ### end Alembic commands ###
