"""add bulk_sales table

Revision ID: 24a83d64ac2a
Revises: 03c770c71e68
Create Date: 2026-06-12 01:59:06.083924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24a83d64ac2a'
down_revision = '03c770c71e68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bulk_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('petrol_pump_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('quantity_liters', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('pso_invoice_number', sa.String(length=80), nullable=True),
    sa.Column('purchase_rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sale_rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_purchase_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('total_sale_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('carriage_charges', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('carriage_paid_by', sa.String(length=20), nullable=True),
    sa.Column('other_expense', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('net_profit', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('vehicle_number', sa.String(length=50), nullable=True),
    sa.Column('driver_name', sa.String(length=150), nullable=True),
    sa.Column('delivery_location', sa.String(length=200), nullable=True),
    sa.Column('delivery_method', sa.String(length=30), nullable=True),
    sa.Column('payment_method', sa.String(length=40), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('delivery_status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['petrol_pump_id'], ['petrol_pumps.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bulk_sales')
    # ### end Alembic commands ###
