"""carriage trip paid_from_account_id for posting

Revision ID: 2df979d3a59d
Revises: 1936b11f5f85
Create Date: 2026-06-12 18:46:52.073275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2df979d3a59d'
down_revision = '1936b11f5f85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carriage_trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_from_account_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_carriage_trips_paid_from_account_id', 'cash_bank_accounts',
            ['paid_from_account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carriage_trips', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_carriage_trips_paid_from_account_id', type_='foreignkey')
        batch_op.drop_column('paid_from_account_id')

    # ### end Alembic commands ###
