"""stock gain/loss adjustments with approval

Revision ID: 3e39e4a421d6
Revises: 09a6a2a54e5c
Create Date: 2026-06-12 13:49:01.615885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e39e4a421d6'
down_revision = '09a6a2a54e5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('petrol_pump_id', sa.Integer(), nullable=False),
    sa.Column('tank_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('adjustment_date', sa.Date(), nullable=False),
    sa.Column('system_stock_liters', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('physical_stock_liters', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('difference_liters', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stock_posted', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('rejection_reason', sa.String(length=300), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['petrol_pump_id'], ['petrol_pumps.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tank_id'], ['pump_tanks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_adjustments')
    # ### end Alembic commands ###
