"""journal entry source linking for auto-posting

Revision ID: 638335d92c57
Revises: e12b1357556e
Create Date: 2026-06-12 15:22:43.422583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '638335d92c57'
down_revision = 'e12b1357556e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_type', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('source_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_journal_entries_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_source_type'), ['source_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_entries_source_type'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_source_id'))
        batch_op.drop_column('source_id')
        batch_op.drop_column('source_type')

    # ### end Alembic commands ###
