"""create core foundation models

Revision ID: 6f64b7cf212e
Revises: 
Create Date: 2026-06-11 16:32:39.021461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f64b7cf212e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('type', sa.Enum('PETROL_PUMP_RETAIL', 'BULK_SALE', 'CARRIAGE', 'OIL_AGENCY', 'HEAD_OFFICE', name='businessunittype'), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('contact_number', sa.String(length=50), nullable=True),
    sa.Column('logo_path', sa.String(length=300), nullable=True),
    sa.Column('ntn_number', sa.String(length=50), nullable=True),
    sa.Column('default_currency', sa.String(length=10), nullable=False),
    sa.Column('financial_year_start', sa.Date(), nullable=True),
    sa.Column('financial_year_end', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('petrol_pumps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_unit_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('pso_account_name', sa.String(length=150), nullable=True),
    sa.Column('cash_account_name', sa.String(length=150), nullable=True),
    sa.Column('bank_account_name', sa.String(length=150), nullable=True),
    sa.Column('manager_name', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_unit_id'], ['business_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('petrol_pumps')
    op.drop_table('companies')
    op.drop_table('business_units')
    # ### end Alembic commands ###
