"""add pump_expenses, lubricant_sales, pump_daily_closings tables

Revision ID: 92c47746819a
Revises: b07a9a449859
Create Date: 2026-06-12 00:58:19.312702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92c47746819a'
down_revision = 'b07a9a449859'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lubricant_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('petrol_pump_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=40), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['petrol_pump_id'], ['petrol_pumps.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pump_daily_closings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('petrol_pump_id', sa.Integer(), nullable=False),
    sa.Column('closing_date', sa.Date(), nullable=False),
    sa.Column('fuel_sale_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('fuel_sale_liters', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('lubricant_sale_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('total_sale_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('cash_received', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('bank_card_received', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('pso_card_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('easypaisa_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('jazzcash_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('bank_transfer_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('credit_sale_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('expenses_paid', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('expected_cash_to_submit', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('cash_submitted_to_head_office', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('difference_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('remarks', sa.String(length=300), nullable=True),
    sa.Column('manager_approved', sa.Boolean(), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['petrol_pump_id'], ['petrol_pumps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pump_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('petrol_pump_id', sa.Integer(), nullable=False),
    sa.Column('expense_category_id', sa.Integer(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('paid_from_account_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('attachment_path', sa.String(length=300), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['expense_category_id'], ['expense_categories.id'], ),
    sa.ForeignKeyConstraint(['paid_from_account_id'], ['cash_bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['petrol_pump_id'], ['petrol_pumps.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pump_expenses')
    op.drop_table('pump_daily_closings')
    op.drop_table('lubricant_sales')
    # ### end Alembic commands ###
