"""agency godown stock flags (to_godown / from_godown)

Revision ID: 956f986a8004
Revises: 2df979d3a59d
Create Date: 2026-06-12 20:07:33.975540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '956f986a8004'
down_revision = '2df979d3a59d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agency_purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'to_godown', sa.Boolean(), nullable=False,
            server_default=sa.false()))

    with op.batch_alter_table('agency_sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'from_godown', sa.Boolean(), nullable=False,
            server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agency_sales', schema=None) as batch_op:
        batch_op.drop_column('from_godown')

    with op.batch_alter_table('agency_purchases', schema=None) as batch_op:
        batch_op.drop_column('to_godown')

    # ### end Alembic commands ###
