"""add pump_purchases and pump_purchase_items tables

Revision ID: b07a9a449859
Revises: 543d814e21d8
Create Date: 2026-06-12 00:48:52.924172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b07a9a449859'
down_revision = '543d814e21d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pump_purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('petrol_pump_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('invoice_number', sa.String(length=80), nullable=True),
    sa.Column('vehicle_number', sa.String(length=50), nullable=True),
    sa.Column('driver_name', sa.String(length=150), nullable=True),
    sa.Column('delivery_status', sa.String(length=20), nullable=False),
    sa.Column('tank_received', sa.Boolean(), nullable=False),
    sa.Column('stock_posted', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['petrol_pump_id'], ['petrol_pumps.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pump_purchase_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pump_purchase_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('tank_id', sa.Integer(), nullable=True),
    sa.Column('quantity_liters', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['pump_purchase_id'], ['pump_purchases.id'], ),
    sa.ForeignKeyConstraint(['tank_id'], ['pump_tanks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pump_purchase_items')
    op.drop_table('pump_purchases')
    # ### end Alembic commands ###
