"""add carriage_trips table

Revision ID: b26a6bdd2d11
Revises: 24a83d64ac2a
Create Date: 2026-06-12 02:47:20.247463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b26a6bdd2d11'
down_revision = '24a83d64ac2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carriage_trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_number', sa.String(length=40), nullable=False),
    sa.Column('trip_date', sa.Date(), nullable=False),
    sa.Column('trip_type', sa.String(length=60), nullable=False),
    sa.Column('business_reference', sa.String(length=40), nullable=True),
    sa.Column('vehicle_ownership', sa.String(length=30), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_number', sa.String(length=50), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('driver_name', sa.String(length=150), nullable=True),
    sa.Column('driver_contact', sa.String(length=50), nullable=True),
    sa.Column('rented_vehicle_vendor_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity_loaded', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('quantity_delivered', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('loading_point', sa.String(length=200), nullable=True),
    sa.Column('unloading_point', sa.String(length=200), nullable=True),
    sa.Column('party_name', sa.String(length=200), nullable=True),
    sa.Column('freight_rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_freight_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('freight_paid_by', sa.String(length=20), nullable=True),
    sa.Column('rent_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('fuel_expense', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('toll_tax', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('loading_unloading_expense', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('driver_expense', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('maintenance_expense', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('other_expense', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('net_profit', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('trip_status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['rented_vehicle_vendor_id'], ['vendors.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('carriage_trips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_carriage_trips_trip_number'), ['trip_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carriage_trips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_carriage_trips_trip_number'))

    op.drop_table('carriage_trips')
    # ### end Alembic commands ###
