"""pump staff salary breakdown (basic + allowances)

Revision ID: bd8f5752d45d
Revises: 1f1126267aec
Create Date: 2026-07-07 14:17:57.376631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd8f5752d45d'
down_revision = '1f1126267aec'
branch_labels = None
depends_on = None


def upgrade():
    # New breakdown columns default to 0 so existing rows stay valid; a
    # server_default keeps the NOT NULL constraint safe on SQLite and MySQL.
    num = sa.Numeric(precision=14, scale=2)
    with op.batch_alter_table('pump_staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('basic_salary', num, nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('food_allowance', num, nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('special_allowance', num, nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('medical_allowance', num, nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('mobile_allowance', num, nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('other_allowance', num, nullable=False, server_default='0'))

    # Preserve each existing employee's agreed pay: put their current
    # monthly_salary into Basic Salary so the total is unchanged.
    op.execute("UPDATE pump_staff SET basic_salary = monthly_salary")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pump_staff', schema=None) as batch_op:
        batch_op.drop_column('other_allowance')
        batch_op.drop_column('mobile_allowance')
        batch_op.drop_column('medical_allowance')
        batch_op.drop_column('special_allowance')
        batch_op.drop_column('food_allowance')
        batch_op.drop_column('basic_salary')

    # ### end Alembic commands ###
