"""pump daily closing credit sales (multiple customers per closing)

Revision ID: c1d2e3f4a5b6
Revises: bd8f5752d45d
Create Date: 2026-07-20 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1d2e3f4a5b6'
down_revision = 'bd8f5752d45d'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('pump_daily_closing_credit_sales',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('daily_closing_id', sa.Integer(), nullable=False),
        sa.Column('customer_id', sa.Integer(), nullable=False),
        sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['daily_closing_id'], ['pump_daily_closings.id'], ),
        sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # Migrate any existing single-customer credit sale into the new line-item
    # table before dropping the old columns, so no historical data is lost.
    op.execute("""
        INSERT INTO pump_daily_closing_credit_sales
            (daily_closing_id, customer_id, amount, created_at, updated_at)
        SELECT id, credit_customer_id, credit_sale_amount, created_at, updated_at
        FROM pump_daily_closings
        WHERE credit_customer_id IS NOT NULL AND credit_sale_amount > 0
    """)

    with op.batch_alter_table('pump_daily_closings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_pdc_credit_customer_id', type_='foreignkey')
        batch_op.drop_column('credit_customer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pump_daily_closings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_customer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_pdc_credit_customer_id', 'customers', ['credit_customer_id'], ['id'])

    op.execute("""
        UPDATE pump_daily_closings
        SET credit_customer_id = (
            SELECT customer_id FROM pump_daily_closing_credit_sales
            WHERE daily_closing_id = pump_daily_closings.id
            ORDER BY amount DESC LIMIT 1
        )
    """)

    op.drop_table('pump_daily_closing_credit_sales')

    # ### end Alembic commands ###
