"""add head_office_expenses table

Revision ID: e3fe106ebd00
Revises: 564967e621af
Create Date: 2026-06-12 01:42:35.750176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3fe106ebd00'
down_revision = '564967e621af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('head_office_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_category_id', sa.Integer(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('paid_from_account_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('reference_number', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('attachment_path', sa.String(length=300), nullable=True),
    sa.Column('is_posted', sa.Boolean(), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['expense_category_id'], ['expense_categories.id'], ),
    sa.ForeignKeyConstraint(['paid_from_account_id'], ['cash_bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('head_office_expenses')
    # ### end Alembic commands ###
