"""add pump_machines, pump_nozzles, pump_tanks tables

Revision ID: eae76e0a20b1
Revises: ad6d3742c762
Create Date: 2026-06-12 00:31:46.332077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eae76e0a20b1'
down_revision = 'ad6d3742c762'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pump_machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('petrol_pump_id', sa.Integer(), nullable=False),
    sa.Column('machine_name', sa.String(length=150), nullable=False),
    sa.Column('machine_number', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['petrol_pump_id'], ['petrol_pumps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pump_tanks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('petrol_pump_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('tank_name', sa.String(length=150), nullable=False),
    sa.Column('capacity_liters', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('opening_stock_liters', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('current_stock_liters', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('dip_reading', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['petrol_pump_id'], ['petrol_pumps.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pump_nozzles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('petrol_pump_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('nozzle_number', sa.String(length=50), nullable=False),
    sa.Column('opening_reading', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('current_reading', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['pump_machines.id'], ),
    sa.ForeignKeyConstraint(['petrol_pump_id'], ['petrol_pumps.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pump_nozzles')
    op.drop_table('pump_tanks')
    op.drop_table('pump_machines')
    # ### end Alembic commands ###
